[tool.ruff]
# 전체적인 설정
line-length = 88
target-version = "py310"        # 프로젝트가 Python 3.10을 사용한다고 가정
exclude = ["build/", "dist/", ".venv/", "migrations/"]  # 검사 제외할 디렉토리들

[tool.ruff.lint]
select = ["E", "F", "I", "B"]     # E: 스타일/포맷 오류, F: 문법/논리 오류, I: import 관련, B: Bugbear 플러그인 규칙
ignore = ["E203", "W503"]         # Black 과 충돌할 수 있는 규칙들은 무시
per-file-ignores = {              # 특정 파일/패턴에 대해 규칙 무시
  "__init__.py" = ["F401"]        # __init__.py에서 'unused import' 오류 무시
}

[tool.black]
line-length = 88
target-version = ["py310"]
# 필요하면 추가: include / exclude 설정 가능

[tool.isort]
profile = "black"
line_length = 88
# import 줄 관련 설정
known_first_party = ["my_project"]       # 프로젝트 내부 모듈명이 my_project면, 먼저 정리하게 함
default_section = "THIRDPARTY"
multi_line_output = 3                    # 줄 나눌 방식, Black과 호환되게